### ISSUE TITLE
Does forloop works?

### ISSUE THREAD

**Issue by ghost** [DougBeney/jekyll-pug#1]
Hello!, I was using your plugin and cant figure out how to use forloops
Thank you!

**Comment by DougBeney** [comment]
Hi, Juliso!

Thank you for trying out the plugin. 

Can you provide some more detail on how far you've gotten so far? Any errors?

Forloops should definitely work. 

Make sure to read the [README](https://github.com/DougBeney/jekyll-pug/blob/master/README.md) carefully.

**Comment by ghost** [comment]
Doug thanks for the fast response!
I was trying to do so:
```pug
ul
  {% for hello in site.hellos %}
    li {{ hello.title }}
  {% endfor %}
```
Because i just found out about this:
```pug
ul
  - for (var i=1; i<=10; i++) {
    li= i + ". Hello"
  - }   
```

**Comment by DougBeney** [comment]
Glad you figured it out.

If you ever need to use Jekyll's for loops, it is still possible. You just made a slight syntax error. 

Here is the correct code:

```
ul
    | {% for hello in site.hellos %}
    li {{hello.title}}
    | {% endfor %}
```

The `|` signals piped text. [Here's some info on how Pug's piped text works](https://pugjs.org/language/plain-text.html#piped-text)

How this plugin works is it first converts the Pug code to HTML and then uses Jekyll's HTML compiler to deal with the template engine code.

Hope you enjoy this plugin and do let me know if you have any other questions!

Cheers.
