### ISSUE TITLE
I required gem declaration in _config.yml

### ISSUE THREAD

**Issue by EricWarnke** [DougBeney/jekyll-pug#10]
Thanks for the awesome plugin. Before I could get Pug to compile for my Jekyll site I had to ensure that in my _config.yml file I had declared the gem. 

Like so:
```
gems:
- jekyll-pug
```

Maybe that will help the next person if it makes it into the docs. I didn't want to make a PR without knowing if my situation was unique or not.

**Comment by DougBeney** [comment]
Hi, Eric! Happy to hear the plugin is helping you out!

You shouldn't be required to declare the gem though. I just ran a test project and I didn't have to do that. 

**Step 1.)** Create a file named `Gemfile` with the following content:

```
source "https://rubygems.org/"

group :jekyll_plugins do
  gem 'jekyll-pug'
  # Add other Jekyll plugins you are using below this line.
end
```

**Step 2.)** Create your index.pug file (with front-matter). 

```
---
---

h1 Welcome to Jekyll-Pug!
```

**Step 3.)** Run the command `bundle install`

**Step 4.)** Run the Jekyll server with `jekyll serve`.

**Comment by EricWarnke** [comment]
Well of course it works now that you looked at it...

Perhaps my actually updating bundler helped. Thanks anyway!

**Comment by DougBeney** [comment]
Glad the issue is resolved! If you ever publish a site written in Jekyll-Pug and want to share it, we started a thread [to do so here](https://github.com/DougBeney/jekyll-pug/issues/6). Once there's a decent list of 2 or more sites, they will be featured in the docs.
