### ISSUE TITLE
Use locally installed pug

### ISSUE THREAD

**Issue by benadamstyles** [DougBeney/jekyll-pug#13]
Hey, thanks so much for making this plugin! I think this might be caused by the dependence on `pug-ruby`, but using a globally installed `pug` is less than ideal, not least because it doesn't work using `nvm`. Would there be a way to make `pug-ruby` look for a `pug` executable in the local project's `node_modules`?

**Comment by DougBeney** [comment]
Good idea. I checked out your issue in Pug-Ruby too. Once I figure out how to implement this, I'll release an update + updated documentation.

**Comment by DougBeney** [comment]
Hi, @Leeds-eBooks 

You can probably get around this problem now with a new project that I have been working on. It's called Jekyll-Bliss.

Its goal is to solve Jekyll's biggest problem (Slow compile times). This will add multi-threading when processing Pug, Sass, and more. It uses Gulp behind the scenes to do so. (The user does not need any sort of gulp config).

It will take away all of the heavy lifting from Jekyll.

It's nearly a drop-in replace for Jekyll-Pug


In the readme, I show instructions for doing a global NPM install. However, it will work locally too!

1. `npm install jekyll-bliss --save`
2. `./node_modules/jekyll-bliss/index.js`

Let me know what you think. :)

https://github.com/DougBeney/Jekyll-Bliss

**Comment by benadamstyles** [comment]
@DougBeney Hey, sorry for the delay – this looks really cool, taking a look now. Thanks so much!
