### ISSUE TITLE
Symlink error when deploying to github pages

### ISSUE THREAD

**Issue by lucasnantonio** [DougBeney/jekyll-pug#15]
My website is building fine locally, but I get an error when deploying to my github pages master

![image](https://user-images.githubusercontent.com/13240286/38461222-d181a236-3aa0-11e8-893e-40745e085f45.png)

My code in `home.pug` is: 

```
---
layout: default
---

| {% include components-sidebar.pug %}    
| {% include section-hero.pug %}
| {% include section-writing.pug %}
| {% include section-work.pug %}  
.dn.db-l
  | {% include section-about.pug %}  
| {% include titles.pug title="*" %}
```

**Comment by DougBeney** [comment]
No support for GitHub Pages. Check out #14 for a workaround.

**Comment by lucasnantonio** [comment]
Thanks! 
Closing, see #14
