### ISSUE TITLE
Include with parameters

### ISSUE THREAD

**Issue by lucasnantonio** [DougBeney/jekyll-pug#17]
Hi, I'm trying to include .pug files and pass parameters to them.

test.pug
```p { include.text }```

layout.pug
```{% include test.pug text="foo"}```

is rendering
```<p>{include.text}</p>```

instead of the expected result
```<p>foo</p>```

any tips why this might be happening?

**Comment by lucasnantonio** [comment]
Never mind, my mistake. 
Includes need {{ }}

**Comment by DougBeney** [comment]
Glad you solved it. Thanks for using Jekyll Pug!
