### ISSUE TITLE
plugin incorrectly compiling {{content}} as plaintext

### ISSUE THREAD

**Issue by taxilly** [DougBeney/jekyll-pug#18]
Almost all of the pages on my site using the `page` layout are compiled as plaintext, while others are not, see image related.
```
bundle    1.16.1
jekyll (3.7.2)
jekyll-pug (1.5.3)
```
https://github.com/ttxi/ttxi.gq/blob/master/_layouts/page.pug
https://github.com/ttxi/ttxi.gq/blob/master/pages/sitemap.pug

![2018-06-19-144126_1366x768_scrot](https://user-images.githubusercontent.com/13081443/41602322-75604adc-73d2-11e8-9478-67ea12f30cde.png)

![2018-06-19-144220_1366x768_scrot](https://user-images.githubusercontent.com/13081443/41602320-7542d862-73d2-11e8-934c-ae05ce863d36.png)

**Comment by taxilly** [comment]
Just rolled back versions and it started working again nvm

**Comment by DougBeney** [comment]
Glad you got it sorted! Keep an eye on [Jekyll-Bliss](https://gitlab.com/dougbeney/Jekyll-Bliss). It's the project that will supersede Jekyll-Pug. It already makes compile time much, much faster.

**Comment by ErikBjare** [comment]
@taxilly Do you remember what you rolled back, exactly?

Looking into a solution for #19
