### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Anenth** [DougBeney/jekyll-pug#2]
When I try to include the pug file, it throws an error. 

`Liquid Exception: No such file or directory - pug in /_layouts/default.html`

This is what am doing: 
```
{% include contact.pug %} 
```

the file `contact.pug` is present on `_includes` folder

**Comment by DougBeney** [comment]
Hi, Anenth!

Thank you for trying out Jekyll-Pug. 

The first thing I will recommend doing is cloning the [jekyll-pug-test repository](https://github.com/DougBeney/jekyll-pug-test) and following the directions on [its readme.md](https://github.com/DougBeney/jekyll-pug-test/blob/master/README.md).

Jekyll-pug-test is a super simple jekyll-pug project that is good for learning how the plugin works and being completely sure if an issue you are experiencing is your fault or not. 

From what it seems with your error code, there's a good chance jekyll-pug isn't installed properly. 

I recommend following the [install directions](https://github.com/DougBeney/jekyll-pug/blob/master/README.md) again and carefully look if there are any errors outputted.

If you've made it this far and haven't pinpointed the error yet, something you can do is create a public git repository with your jekyll-pug project and I could look into the code. 

Best of luck!

**Comment by DougBeney** [comment]
Hi, Anenth. 

Fix the issue yet?

**Comment by Anenth** [comment]
@DougBeney I havnt tried it till now, I will try it this week.

**Comment by Anenth** [comment]
@DougBeney I havnt tried it till now, I will try it this week.

**Comment by DougBeney** [comment]
Hi, Anenth. Any update?

**Comment by tmartin2089** [comment]
@Anenth try `npm install -g pug-cli`

@DougBeney had similar error, reading through compile.rb for the gem it doesn't seem to reach the error flag at line 70

`raise ExecutableError, 'No pug executable found in your system. Did you forget to "npm install -g pug-cli"?'`

Coworker with same version of ruby, jekyll etc, didn't have this error, but he's a heavy pug user so it was likely already globally installed.

**Comment by Anenth** [comment]
` npm install -g pug-cli` helped but am facing another problem 

![screenshot 2017-08-19 11 48 21](https://user-images.githubusercontent.com/1499218/29484063-7902cb6c-84d4-11e7-9d05-8825404880ef.png)

not able to include a html file from a pug file

**Comment by DougBeney** [comment]
Ah, I see the problem.

Change this line:

`{% include svg-icons.html %}`

To this:

`| {% include svg-icons.html %}`

With this plugin, Pug processes your files before Jekyll does. Pug is trying to turn `{%` into an HTML tag, which is not possible, so it's throwing an error. Adding the `|` (piped text symbol) at the start of a line let's Pug know that you want to write plain text. 

For more information on how Pug handles plain-text, check out [this part of the docs](https://pugjs.org/language/plain-text.html).

**Comment by Anenth** [comment]
@DougBeney Ho!!! I forgot about it. Thanks
