### ISSUE TITLE
Liquid support in jekyll-bliss ?

### ISSUE THREAD

**Issue by ianmihura** [DougBeney/jekyll-pug#21]
Hey there! I'm rising the issue here, cause in your **jekyll-bliss** repo you don't seem to have issue tab enabled.

Anyhow, the issue I am getting is reproducing itself both in jekyll-pug and jekyll-bliss
It's this type of error, when I try to compile a piece of `liquid ` code (with the | selector)
```
Error: _includes\this-is-a-silly-hack.pug:11:1
    9|
    10|         | {% if true %}
  > 11|             p this
--------^
    12|         | {% endif %}

unexpected token "indent"
```

Doesn't seem to allow for liquid elements? Same thing happens when using a `{% for ... %}`.
Yet the `| {% include ... %}` works just fine. 
I've also tried with no pipe, with two pipes, with no `{%%}`, to different results, yet none a successful compile.

Do you have any insight into this? Developing jekyll with no `liquid` support is a definitive killer.

**Comment by DougBeney** [comment]
Fixed the issues tab. Good catch. :)

Yeah, so your problem there is indenting into a pipe. Do this instead:

```
| {% if true %}
p this
| {% endif %}
```

**Comment by ianmihura** [comment]
Nice, thanks! Seems like foolish mistake after all.

**Comment by DougBeney** [comment]
No problem! Thank you for using this software.
