### ISSUE TITLE
Pug not respecting Jekyll custom folder layout

### ISSUE THREAD

**Issue by HaoZeke** [DougBeney/jekyll-pug#5]
So I use a _pages folder setup where .html and .md files in _pages are compiled to the site root...

However when I place a pug file (eg. pug.pug)  in _pages, it is outputted in the site as /_pages/pug/index.html instead of /pug/index.html

I suppose this is because the pug compiler outputs directly to the public folder instead of compiling to static html before processing with jekyll...

Any workarounds would be greatly appreciated..

**Comment by DougBeney** [comment]
Hi! 

Strange error. I am not able to reproduce it. 

Here is my project setup. Let me know if yours is any different.

**Project Structure**

- _pages/
    - sports/
        - baseball.pug
- _site/
    - sports/
        - baseball.html
- _config.yml
- Gemfile


**_config.yml**

```yml
source: "_pages"
```

**_pages/sports/baseball.pug**

```
---
---
    
p Baseball is a fun sport.
```

**Gemfile**

```
source 'https://rubygems.org'

group :jekyll_plugins do
    gem 'jekyll-pug'
end
```

The only thing I see that is different is that you have Jekyll generate folders with `index.html`s for each page created. How did you do that?

**Comment by HaoZeke** [comment]
Interesting!

So I tried with source: "_pages"
That gave exactly what was expected...
For the folders you just need to set the permalink style...


The problem I was facing can be reproduced using the old way of including folders, i.e:

include:
  - _pages
  - '_pages/*.*'

It's interesting but, not relevant to the plugin since it's depreciated anyway...

Again, thanks a ton...

**Comment by HaoZeke** [comment]
Hi. There's a bit of an unforseen issue with using source to include pages...

So I have index.md and a 404.html in my site root...
ie.

src/index.md
src/_pages/pug.pug

Now pug is processed ok, but the index.md is getting left behind..

**Comment by HaoZeke** [comment]
Sorry, fixed with include : ['_pages']

**Comment by DougBeney** [comment]
Glad you solved the issue :smile:
