### ISSUE TITLE
Extremely long build times

### ISSUE THREAD

**Issue by taxilly** [DougBeney/jekyll-pug#7]
Since switching over to this plugin my build times have gone from 20-ish seconds to over 220 seconds, most of the time taken up by pug compiling, is there any way to speed up this process?

**Comment by DougBeney** [comment]
While it is true that this plugin increases the build time of a project, I have never experienced that long of build times. For the [Jekyll-Pug Website](https://github.com/DougBeney/jekyll-pug-website) it takes 4.049 seconds for a complete build. Can you please let me know how big your project is in comparison to the Jekyll-Pug website? 

I've just started working on a new version of Jekyll-Pug to add new features and hopefully increase performance. 

Thanks for using the plugin!

EDIT: Fixed link

**Comment by taxilly** [comment]
https://github.com/twentytwoo/mainstrea.ml

I haven't fully ported the site, but just changing the default layout to pug causes the build time to spike :/

**Comment by DougBeney** [comment]
Interesting. I'll try to get out a version this week to hopefully fix the performance issues.

I'm assuming that this long build time is only when you initially run the site. Once it's running and you modify a file, it shouldn't take the same amount of time to build again, right?

**Comment by taxilly** [comment]
Long build times don't occur when editing the SCSS, editing the pug/HTML however does.

**Comment by DougBeney** [comment]
And just for my information, what version of Node are you running? You can type `node -v` to figure that out.

**Comment by taxilly** [comment]
```
home> node -v
v6.11.3
```

**Comment by DougBeney** [comment]
Just released Jekyll-Pug version `1.0.1` today. 

Many great improvements you can read about in [the changelog](https://github.com/DougBeney/jekyll-pug/blob/master/CHANGELOG.md), such as native Pug includes becoming fully functional. 

Speed should also be greatly improved, so I hope it helps you out. 

If you're using a Gemfile, you could simply type `bundle update` to get the new version.

**Comment by taxilly** [comment]
220 second+ build time still present, I've narrowed it down to the 100+ posts on my blog that's causing the issue, removing all the posts sends to build time to less than a second.

**Comment by taxilly** [comment]
Just started afresh and got the build time down to 30-ish seconds with all posts, good job on the plugin 👍

**Comment by DougBeney** [comment]
Just want to report that there is a new update that I have a feeling will take your 30 second build time to 6 seconds or less.

**Comment by taxilly** [comment]
Before:
```
      Generating... 
pug version: 2.0.0-rc.4
                    done in 145.844 seconds.
```

After:
```
      Generating... 
pug version: 2.0.0-rc.4
                    done in 5.966 seconds.

```
I damn near spat out my tea, great job! What did you do?

**Comment by DougBeney** [comment]
Epic! Power of caching, right?

**Comment by DougBeney** [comment]
Hi, @twentytwoo!

Good news! I've been working on a project to bring down Jekyll build times even more if you are still interested.

It is called [Jekyll-Bliss](https://github.com/DougBeney/jekyll-bliss).

It has already reduced my build time by 63%!
